export const phrasalVerbs_api = [
    {
        id: "1",
        phrasalVerb: "inicioo",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "2",
        phrasalVerb: "oward to",
        example_1: "I'm aefgafdfind a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "3",
        phrasalVerb: "Toasefasdfaasdfadsfasdffasdfook foward to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "4",
        phrasalVerb: "owardadsf tadsfasdfo",
        example_1: "I'm aefgafdfind a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "a",
        phrasalVerb: "Toaoward to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "5",
        phrasalVerb: "owaasdfrd to",
        example_1: "I'm aefgafdfind a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "6",
        phrasalVerb: "Tok foward to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "7",
        phrasalVerb: "oward tdfgsdfgsdfgo",
        example_1: "I'm aefgafdfind a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "8",
        phrasalVerb: "Toasefasdfasdfasdfook foward to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },{
        id: "9",
        phrasalVerb: "Td to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "10",
        phrasalVerb: "Toasefasdfasdfasdfook foward to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "11",
        phrasalVerb: "d to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "12",
        phrasalVerb: "owarasdfasdfasdfasdfd to",
        example_1: "I'm aefgafdfind a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "13",
        phrasalVerb: "Td to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "14",
        phrasalVerb: "owaasdfasdfasdfasdfrd to",
        example_1: "I'm aefgafdfind a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "15",
        phrasalVerb: "Td to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "16",
        phrasalVerb: "owarasdfasdfasdfasdfd to",
        example_1: "I'm aefgafdfind a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "17",
        phrasalVerb: "Toasefasdfasdfasdfook foward to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "18",
        phrasalVerb: "oward to",
        example_1: "I'm aefgafdfind a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "19",
        phrasalVerb: "Toasefasdfasdfasdfook foward to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },{
        id: "20",
        phrasalVerb: "Toasefasdfasdfasdfook foward to",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    },
    {
        id: "21",
        phrasalVerb: "fim",
        example_1: "I'm looking foward to find a brand new job",
        example_2: "I look foward to see you again",
        translation_1: "hha hahaha ahaha haha",
        translation_2: "hu  hu  huuuuhu   hu huhu",
    }
];